trigger:
  branches:
    include:
      - main  # Trigger the pipeline for changes in 'main' branch

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'scripts/Authenticate.ps1'  # PowerShell script to authenticate
    pwsh: true

- task: PowerShell@2
  inputs:
    filePath: 'scripts/Publish-Report.ps1'  # PowerShell script to publish PBIX
    arguments: '-pbixPath $(System.DefaultWorkingDirectory)/reports/YourReport.pbix'  # Replace with actual report path
    pwsh: true

- task: PowerShell@2
  inputs:
    filePath: 'scripts/Refresh-Dataset.ps1'  # PowerShell script to refresh dataset
    pwsh: true





