trigger:
  branches:
    include:
      - main

stages:
- stage: Dev
  jobs:
  - job: DeployToDev
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'C:\Users\MVankudoth\Downloads\PowerBI-CI-CD\Reports'
        arguments: '-pbixPath $(System.DefaultWorkingDirectory)/reports/DevReport.pbix -workspaceId DEV_WORKSPACE_ID'
        pwsh: true

- stage: Test
  dependsOn: Dev
  jobs:
  - job: DeployToTest
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'C:\Users\MVankudoth\Downloads\PowerBI-CI-CD\Reports'
        arguments: '-pbixPath $(System.DefaultWorkingDirectory)/reports/TestReport.pbix -workspaceId TEST_WORKSPACE_ID'
        pwsh: true

- stage: Prod
  dependsOn: Test
  jobs:
  - job: DeployToProd
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'C:\Users\MVankudoth\Downloads\PowerBI-CI-CD\Reports'
        arguments: '-pbixPath $(System.DefaultWorkingDirectory)/reports/ProdReport.pbix -workspaceId PROD_WORKSPACE_ID'
        pwsh: true






